### ISSUE TITLE
Lock screen problem

### ISSUE THREAD

**Issue by Blackstorm99** [Moyster/android_device_meizu_m2note#41] opened 2016-12-12 23:27 UTC
The only bug I found is related with the lock screen. When I set the pattern, pin or password the phone unlocks directly to the home screen or the app I've been using before without asking me for any kind of password. Right After rebooting the lock screen appears and also if I set the swipe to unlock option the lock screen works normally.

**Comment by franci22** [comment] 2016-12-13 20:18
did you enable Smart Lock?

**Comment by Blackstorm99** [comment] 2016-12-13 20:33
Nop

**Comment by franci22** [comment] 2016-12-14 17:52
it's strange. check your Device administrators (Settings -> Security) and Trust agents (Settings -> Lock screen).

**Comment by Moyster** [comment] 2016-12-14 17:55
hello there,
I think the last time I tried to set a password/scheme/pin unlock was around September :D  
I'm pretty sure it was working, maybe I didn't understand tho.

If you set a password/unlock scheme, you need to reboot once for the password/unlock scheme to be enabled ?

**Comment by franci22** [comment] 2016-12-14 18:26
I have a scheme unlock and I don't have any type of problems.

**Comment by Moyster** [comment] 2016-12-14 18:41
I'll probably close this issue if OP doesn't answer.

@Blackstorm99 : did the problem still exist if you do a full wipe ? (just make a backup, wipe clean, flash cm-12.1 and test setting a lock)
If you can't reproduce the bug on a clean build, well :D you know what to do ! ;)

@franci22 Thanks for your help, it's greatly appreciated. don't hesitate to send a mail if you want to invest a little time and effort on this device, actually it'd be great to have a small "dev group" just for the sake of motivation ;)

**Comment by Blackstorm99** [comment] 2016-12-14 19:00
Actually is a translation issue. In settings/lock screen there is an option called "power button instantly locks"  but in spanish it is translated as "bloquear al encender"  which means "lock when you are booting the phone". I think that the correct translation should be "desbloquear instantáneamente con el botón de encendido"

**Comment by Moyster** [comment] 2016-12-14 19:06
Oh :D Well, I think you might want to tell cyanogenmod people about it ( CM bug tracker :  https://jira.cyanogenmod.org/secure/Dashboard.jspa ).  

Good to know it's solved tho :)  
Did you switch to english to notice that ?

**Closed** 2016-12-14 19:06 UTC

**Comment by Blackstorm99** [comment] 2016-12-14 19:09
Yes I did
