### ISSUE TITLE
Issue with offline charing

### ISSUE THREAD

**Issue by numpea** [Moyster/android_device_meizu_m2note#30] opened 2016-11-18 11:01 UTC
first i have clean flashed two times build 14
when i power off the phone and plug it to offline charge the device turn on and start without going into offline charging mode somtimes when i unplug it after the device turns on a reboot occures 
just with last build (14) 
good luck :)

**Comment by Moyster** [comment] 2016-11-20 12:14
Hello, well I gave a look at this problem too, since I made a new release and it seems this bug appeared with the "usb charge only" fix.
It would be great if you could try a few things with the rootdir files, It's probably where the problem is.

I'm not gonna be able to invest much time into this, my homelab just had hardware failure and I'm gonna need to buy a new motherboard, and that's not something I wanted to fit in my schedule =/

You can send a pm if you need advices, good luck :)

**Comment by numpea** [comment] 2016-11-20 12:51
Don't bother yourself it's not so important i will gave a look and pm you next week when i'm back to home 
Have a great day :)

**Comment by Moyster** [comment] 2016-11-20 13:03
Hum actually it kind of is, globally and personally, it sucks, if the phone's battery is empty, the phone will shutdown, if the phone is plugged at that time, it will boot in offline charging mode but it doesn't work so it'll boot the rom, if there's not enough charge, it will bootloop, and keep going on like that =/
It worked before, it should still work now, and if not I'll try reverting the charge only on usb fixes.

I'm pretty sure it's mostly a bad configuration and it can be fixed by tweaking these files ;)

Fix a bug, fix my heart, I should have said that on the rom thread :smile:

**Comment by numpea** [comment] 2016-11-20 13:22
i didn't know that it will bootloop if there is not enough charge, i said it's not important because the rom boots and the phone charges normaly i will look into it :p

**Comment by Moyster** [comment] 2016-11-20 13:29
Be brave, do it :)

I'm about to go to Paris on a rainy sunday to buy a motherboard, FML.

**Comment by andrea2107** [comment] 2016-11-22 19:06
might not be important...but i have the same strange bug on my custom kernel for xiaomi redmi note 2, so it could not be related to ramdisk

PS: the funny fact is that if i unplug the usb cable from the phone while offline charging...it just shuts down like it was in offline charging mode :P

**Comment by Moyster** [comment] 2016-11-22 19:12
Oh... Well I thought of it, since it seems the November security bulletin changed/backported a lot of things. Tbh that last Sec Bulletin is real troubles, did you try using an old version of your kernel ?

I might compile an older tree and see if anything introduced that this weekend, actually didn't set up my build env on the homelab and I can't compile LP on my desktop (ubuntu 16.10, no openjdk7 packages available)

Is that a mediatek phone too ? If so, I wonder if this trick would do : 
https://github.com/fire855/android_system_core-mtk/commit/f0b3162d1928364d01787884b3fa415adc3a72ac

**Comment by andrea2107** [comment] 2016-11-22 19:27
oh,my problem is only kernel side :P (others don't have this issue with other kernels,well,our custom kernel already has lots of issues :P)
btw redmi note 2 is powered by mt6795
also in include/mach/mt_boot_common.h  KERNEL_POWER_OFF_CHARGING_BOOT = 8 is already set,so that's not the problem so far

**Comment by Moyster** [comment] 2016-11-22 19:37
Well numpea seems to say the problem appeared on my build (read: kernel) since build 14. So it seems to confirm the bug lies in the recent changes, did you merged the 3.10.104 ? I think the bug only appeared after that on my branches. It narrows down a bit more to some specific commits.
I guess @AlexLartsev19 could help us track the problem :)

**Comment by andrea2107** [comment] 2016-11-22 19:39
yeah,i merged 3.10.104! may be related to that! i'll investigate further :)

**Comment by AlexLartsev19** [comment] 2016-11-23 11:23
@Moyster, what i should do? :P

**Comment by Moyster** [comment] 2016-11-23 11:55
If you could find the problematic commit in the kernel because it seems to be because of that, that the charge offline mode is broken (plug the phone when offline > it boots > unplug > it instant shutdown) :)

**Comment by AlexLartsev19** [comment] 2016-11-23 12:07
Ok :P

**Comment by AlexLartsev19** [comment] 2016-11-23 14:28
@Moyster, offline charging mode not working from October.
Some guyse from 4pda.ru tested my blood kernel (r.1.1 and r.1.2). OCM work on r.1.1(2016-10-02), but not working on r.1.2(2016-11-09)

**Comment by Moyster** [comment] 2016-11-23 14:30
Yep, seems like that's around the 3.10.104 kernel update =/

**Comment by AlexLartsev19** [comment] 2016-11-23 14:31
Maybe :c

**Comment by Moyster** [comment] 2016-11-23 14:35
It would be great if you could build a kernel and try and revert some commits, so we can fix it :) I'll reward you with something something on Gdrive :D

**Comment by andrea2107** [comment] 2016-11-23 14:39
moyster,if you need something to build on,i got a dedicated server( idk when it will expire but it's still on) with lots of horsepower and 32 gb of ram,i am not using it a lot so i can give you an user with sudo permissions :P

**Comment by AlexLartsev19** [comment] 2016-11-23 14:41
@andrea2107 i need a server :P

**Comment by Moyster** [comment] 2016-11-23 14:43
Sweet prince :')
Well, I'll fix mine eventually, but in the mean time if I can build LP off yours, I would appreciate it ;)

Let's find why that kernel is retarded first, then I'll probably make a final build =)

@AlexLartsev19 servers are for people who are named moyster, is your real name "mister" ? haha

**Comment by andrea2107** [comment] 2016-11-23 14:50
give me your mail so i can send you server details :P

**Comment by Moyster** [comment] 2016-11-23 14:54
oysterized@gmail.com (it's on my main page :P )

I think I pinpointed my homelab issue, a 2010 HDD that froze the entire system when it was accessed.
Sad thing is, it was holding my /home partition, a shitload of sources, but nothing "critical" that I don't have backups of...
Good thing is, 6 years 24/7, I think I got my money back on investment :D 

(best part is, about half a Tb to download on a ADSL line now :) :) :) :) :) :) )

**Comment by andrea2107** [comment] 2016-11-23 14:57
sent you a mail

**Comment by Moyster** [comment] 2016-11-23 15:09
Seems like hotmail doesn't accept to deliver my answer, huh, but thanks :)

**Comment by AlexLartsev19** [comment] 2016-11-23 15:44
@Moyster , OCM trouble not associated with Linux-3.10.104 patch :)

**Comment by andrea2107** [comment] 2016-11-23 15:59
@AlexLartsev19 do you know where's the issue? i want to fix it on my kernel too :P

**Comment by AlexLartsev19** [comment] 2016-11-23 16:05
Nope, now i think, which commit can destroy offline charging :new_moon_with_face:

**Comment by mbskykill** [comment] 2016-11-23 16:36
hello..l want to build  cm13  .can   the kernel source of 6.0  to boot  now ?  thanks

**Comment by AlexLartsev19** [comment] 2016-11-23 16:41
Yes

**Comment by mbskykill** [comment] 2016-11-23 16:45
ok .thanks for your post.

sorry for my bad English.

thanks  for your (moyster .alexendor .and.....)  jobs .

**Comment by Moyster** [comment] 2016-11-23 18:35
@andrea2107 It seems we have not much commits in common, and since you stated it was only happening on your device with your custom kernel (but not with stock) I checked around the dates it was possibly introduced, could it be this commits that messes with the boot modes ?
https://github.com/andrea2107/android_kernel_xiaomi_hermes/commit/45b55912914fc4d4364a2cec975d2200e4ccf5dd
https://github.com/andrea2107/android_kernel_xiaomi_hermes/commit/f0014302d86d5ff3a4aed4dbff20eee609e1559a

Would be good to ask the P8000 (elephone) community, see if they have similar problems ( @visi0nary )

**Comment by Moyster** [comment] 2016-11-23 18:46
To be honest I don't even know what that "kill gcc dep" commit does, but I'm probably give it a try and revert this because we explicitely rely on GCC >= 4.9 since we use CC_STACK_PROTECTOR_STRONG .
I really should stop being a lazy fck and start using branches more to keep at least the kernel repo -sane-. FML.

Anyway, @andrea2107 , did you receive my mails or is hotmail really blocking mails from a gmail adress ?? x)
If by any chance you can add me on Hangouts, I'm on for the evening ;)

**Comment by andrea2107** [comment] 2016-11-23 18:56
oh,send mails to andrea210701@gmail.com,my gmail address sometimes show my old not working hotmail address(i can use it as an alias xD )

**Comment by visi0nary** [comment] 2016-11-24 14:25
No issues here whatsoever. OCM works and will just show the battery icon, booting it afterwards and unplugging leaves the phone on. Kernel 104

**Comment by Moyster** [comment] 2016-11-24 18:08
Well, seems like it's the verifiedbootstate hack that prohibits LP from booting fine in OCM, I can confirm having the very same bug on both MM and N (cm13.0 / 14.1).
Thanks @AlexLartsev19 for investigating :)

**Comment by mbskykill** [comment] 2016-11-24 18:27
good !!
　∧＿∧　∧＿∧
(( ・∀・ ))・∀・) )
`＼　　 ∧ 　　ノ
　/　　｜/　　｜
（＿ノ＿)_ノL＿)

**Comment by Moyster** [comment] 2016-11-24 22:43
That smiley is kawaii xD
Well, I'll close the issue :) we did it ;)

**Closed by Moyster** 2016-11-24 22:43 UTC

**Comment by andrea2107** [comment] 2016-11-26 16:19
hell yeah,got adb working,but still not booting :(


2016-11-24 23:43 GMT+01:00 Moyster <notifications@github.com>:

**Comment by scafroglia93** [comment] 2016-12-04 02:30
@andrea2107you're a fucking kangers, let lose and especially look at "his" kernel source, the autorship not exist

@Moyster I hope you can understand, this is a big problem for open source

**Comment by Moyster** [comment] 2016-12-04 10:09
Well, to be honest I saw that issue brought back to my incoming mails... Don't make me scared like that OMG :`| offline charging is GONE OKAY ?? :'(

I'm not gonna blame @andrea2107 because he's young, but it's true that young people doesn't seem to realise the authorship is how contributors cope with "recognition".
"Yes, but it's only cherry-picking / changing a var size / defconfig"... which wouldn't be so easy to replicate if the original change didn't exist or if it was privately sourced or sold under a licencing fee.

On the other hand, some people knows shit clue about git... it's not the best way to do, but what's worse than not respecting authorship is not letting people learn (just cry a bit on Andrea, I did that on @AlexLartsev19 and he rebased his work properly and I felt like a dick afterward :P )

btw @Scafroglia93 , did you read the issue here ? Seems like the "ro.verified.bootsate" hack by francisco breaks the Offline Charging Mode, if by any chance you could forward the information, maybe the patch can be made better / working for mediatek platforms too :)

Best regards.

**Comment by AlexLartsev19** [comment] 2016-12-04 10:45
@Moyster , After the event i use cherry-pick :new_moon_with_face:

**Comment by Moyster** [comment] 2016-12-04 19:45
@AlexLartsev19 : 💯 / 💯  💃 

btw @scafroglia93 : "you're a fucking kangers" is it @andrea2107 you targeted or "kangerS" and I should feel offended ? Tbh, none of you answered and I'm wondering why the drama is on my own kernel issue tracker :? How am I related to all this ? XD

**Comment by Moyster** [comment] 2016-12-05 11:32
Ok, last chance to "make it right", @scafroglia93 edit your message to make it less ambiguous or I'll simply delete everything, despite not caring about hosting your drama, you're simply being an overly dramatic dick here (note you're also showing your disrespect to me doing this here, and not clarifying i'm "not included" in your rant).  
  
Btw, you once offered for help but never answered a single PM just to say "no sorry" or whatever, and everytime you cross my path, you can't seem to get down those high horses you're riding unless I show you the dirt you missed ( https://github.com/visi0nary/android_kernel_elephone_p8000/pull/26 talking about this primarly but hum... :) )
  
Furthermore @andrea2107 's email was posted a couple messages ago, you couldn't make this clearer you were looking for troubles posting this here instead of being a grown man(/woman/person, whatever) and sending him a simple mail looking for answers.  

And it gets even worse when I see this : https://github.com/andrea2107/android_kernel_xiaomi_hermes/issues/7 "KANG" olala, you learned that word recently or what ? Did you even try and contact THE PERSON YOU CRY ABOUT before acting like the youngest retarded kid there ever was on github ??  

I'm not even related to that story, I don't even know why I had to react, but eventually it got me so pissed you should think to yourself, how childish and retarded can I get why my ego talks.

FFS is the internet the only way some people have to prove they exists....

**Comment by scafroglia93** [comment] 2016-12-05 16:54
I don't delete anything. People who do kang not deserve the attention of anyone. If you'd like to come and steal your job? I sold P8000 thus it's no longer my problem...

Ok, i'm a retarded kids but don't forget this: You have cherry-pick all the commits pushed by me into your kernel

Well done!

**Comment by visi0nary** [comment] 2016-12-05 16:58
Cherry picking is the exact opposite of kanging to be fair. You give full credits to the owner with that, so I'm not sure what you are aiming at.

**Comment by scafroglia93** [comment] 2016-12-05 17:02
My question is addressed to those who continue the practice of the kang. I have nothing against @Moyster or you @visi0nary

**Comment by Moyster** [comment] 2016-12-06 12:47
@scafroglia93 : If I tell you I feel aimed at by your comments and ask you to edit them or I'll delete the whole drama, there's a reason.  
"you're a fucking kangers, let lose and especially look at "his" kernel source" ", I'm not Shakespeare but when you use plural followed by a subordinate conjunction, this means you either do wierd "inconscient" mistakes or you initially also put me in the bag. "especially" and "his" emphasis on @andrea2107 being worse than me, but the way you write involves me too.  
  
Now, on a para-verbal level, I still hold the same points, why do you come here and write ambiguous comments if I have NOTHING RELATED TO THAT STORY ?  
FURTHERMORE IF I ALREADY GAVE YOU CREDIT BOTH ON XDA AND THANKING YOU ON PULL REQUESTS YOU DONT EVEN DO FOR MY OWN DEVICE.  

Think about that, you pulled code, code is not dumb or smart, code is code, you're acting like a retarded kiddo, because you stalk a 15 years old "trying to learn" kid you RANT AGAINST on SOMEONE ELSE'S UNRELATED GITHUB instead of trying IN THE FIRST PLACE to send that PERSON/HUMAN a fuckin EMAIL telling him WHAT HE DID WRONG instead.
Did you just consider reaching him ? NO ? This proves my point, you're partially brain damaged or retarded, please don't mention your age because the older you are, the worse it get to ACT LIKE THIS.

>> People who do kang not deserve the attention of anyone
He did kang, he doesn't deserve attention, I don't even have to argue... you said that yourself.

>> I sold P8000 thus it's no longer my problem...
You even asked if I wanted to have kernel support from you, but obviously you forgot I told you I was better off reviewing your changes and pulling them if I felt like it?

>> Ok, i'm a retarded kids but don't forget this: You have cherry-pick all the commits pushed by me into your kernel
I didn't pull everything, but more precisely, I reviewed the changes and gave some testing time to it. but ?! Don't you see the difference between WORK and your BEHAVIOR ? I do acknowledge there is "smart" retarded kid, but how do you call a grown-up like you doing so much drama ?  

So what's next you freaking genius ? You want to burn @andrea2107 on public place ? You're gonna act like a dick whenever you faces the same kind of frustrations in real life ?  

It's great to see for whatever reasons you came here, maybe looking for arbitration yet I'm nobody mate, especially not the FSF, but think of it, if you get shitted on here by me, you prolly did something wrong (ie. stalking and harrassing a 15 years old kiddo instead of contacting him in private in the first place, is just about how fucked up this situation is).

I won't delete nor answer you anymore, I'm currently busy (exam weeks) so go ahead and make drama somewhere else, I don't want that distraction to be notified in my mailbox.

**Comment by andrea2107** [comment] 2016-12-06 12:56
I think that's only bad english
Btw i know i should give right autorship in those commits,but i'm not going to do it anytime soon(for now) as i have other things to do in my Life :D

Btw don't worry,i will delete that messy repo when i buy a new device or i sell my actual device,that's Just a learning repo that i made to learn how kernels are made,and i discovered lots of things(how to add governors or io schedulers),well i learned how to do it and posted the result on xda without taking any Credit(i didn't do anything important) , Just ignore that repo and carry on as i will delete that repo when i will discontinue my project
